site: https://remotionevents.webflow.io
targetHost: https://www.remotionevents.com
robotsTxt: |
  User-agent: * 
  Allow: /
  Disallow: /example-disallow
  Sitemap: https://www.remotionevents.com/sitemap.xml
redirects: |
  /old-home /ru 301
  /ua/ua /ua/home 301
  /ru/ru /ru/home 301
# OR - robotsTxt: "User-agent: * \nDisallow: /  \nSitemap: https://pages.doorstead.com/sitemap.xml"
headers: |
  https://:project.pages.dev/*
    X-Robots-Tag: noindex
  /*
    Strict-Transport-Security: max-age=31536000
    X-Frame-Options: SAMEORIGIN
  /sb_assets/*
    X-Robots-Tag: noindex, nofollow
  /sb_static/*
    X-Robots-Tag: noindex, nofollow
